### ISSUE TITLE
need help adding barriers that affect cargo bikes

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#10]

**Comment by sensescape** [comment]
Just added:
.node[barrier='cycle_barrier']{
    marker-width: 20;
    marker-fill: #ff0000;
    marker-line-color: darken(#ff0000, 10%);
  }

Question for Emil:
Is this detailed enough or need to add access=no or foot=yes?

**Comment by emiltin** [comment]
for a node, i guess this is ok
