### ISSUE TITLE
buildings - decide what to show per zoom

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#13]
http://wiki.openstreetmap.org/wiki/Key:building

**Comment by sensescape** [comment]
currently showing:
  .buildings[railway='station'],
  .buildings[shop='mall'],
  .buildings[amenity='theatre'],
  .buildings[amenity='university'],
  .buildings[amenity='hospital'],
  .buildings[amenity='public_building'] {
      polygon-fill: #cfcfcf;
  }

**Comment by emiltin** [comment]
townhalls
stadiums
