### ISSUE TITLE
need help fixing ferries

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#15]
still drawing

currently using:
# copenhagen_line[bicycle='yes'][route!='ferry']

**Comment by nvkelso** [comment]
Can you reattach the image, please? It didn't go through.

**Comment by sensescape** [comment]
![screen shot 2013-05-10 at 11 44 07 am](https://f.cloud.github.com/assets/466585/489801/c37d7dd0-b9a5-11e2-9a30-88fd8c3bd25a.png)

**Comment by sethfitz** [comment]
Addressed by setting the `line-width` of `::bike_outline` and `::bike_inline` to 0 and removing `#copenhagen_line[bicycle='yes'][route!='ferry']` (because the prior `#copenhagen_line[bicycle='yes']` captures ferry routes).
