### ISSUE TITLE
add tunnels and bridges

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#16]
Need help organizing tunnels and bridges, see how it's drawn in toner

**Comment by sensescape** [comment]
this gives me an error:
#z15plus-roads[kind='highway'][is_tunnel='yes']{
  ::road_outline{ line-width:12; line-color:#e1e5e5; line-opacity: 0.4; }
  ::road_inline{ line-width:6; line-color:#e1e5e5; line-opacity: 0.4; }
  }

**Comment by sensescape** [comment]
Try to get this to render when restructuring.

**Comment by sethfitz** [comment]
These seem to be working properly now.
