### ISSUE TITLE
Style Green Areas

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#17]
- [x] amenity=graveyard
- [x] landuse=cemetary
- [x] landuse=reservoir
- [x] landuse=meadow
- [x] leisure=garden
- [x] leisure=stadium
- [x] leisure=playground
- [x] leisure=golf_course
- [x] tourist=zoo
- [x] surface=grass
- [x] natural=wetland
- [x] landuse=farmland
- [x] landuse=allotment
- [x] natural=sand
- [x] natural=beach

**Comment by sensescape** [comment]
graveyards as parks in copenhagen:
http://www.ibikecph.dk/#!/x5nll.7gznh/

**Comment by sensescape** [comment]
beaches:
http://www.ibikecph.dk/#!/x4yb3.7iuak/

**Comment by sensescape** [comment]
all types above have been added, now need to style with new color or pattern fill

**Comment by emiltin** [comment]
the following are probably not green in color:
sand
beach
allotment
reservoir
playground

**Comment by sensescape** [comment]
done
