### ISSUE TITLE
Add footpaths

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#2]
![Screen Shot 2013-04-24 at 9 38 26 AM](https://f.cloud.github.com/assets/466585/422811/8e8904c0-ad37-11e2-8050-d74137eabc19.png)

footpaths where you can walk your bike

**Comment by sensescape** [comment]
brown dashed lines

**Comment by emiltin** [comment]
the paths shown with small red dots are also footways where you can usually push your bike.
but note that some footpaths does not allow pushing bikes, this is indicated by bicycle=no. this is the case for example in the botanical garden.
