### ISSUE TITLE
Icons and Labels for Places of Worship

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#21]
specific to religion

**Comment by sethfitz** [comment]
[.place_of_worship[`religion=*`]](http://taginfo.local:8080/keys/religion#values)

**Comment by sensescape** [comment]
done

![screen shot 2013-05-24 at 5 11 03 pm](https://f.cloud.github.com/assets/466585/563347/a1531afa-c4cf-11e2-8b4c-2b1c462045d0.png)
