### ISSUE TITLE
Design foot paths, differentiate where you can push your bike

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#25]
highway=steps
highway=footway
highway=pedestrian

in combination with bicycle no and bicycle yes

show places where you can push only push your bike in path - dotted line or

**Comment by sensescape** [comment]
Foot paths added, need to style now

**Comment by emiltin** [comment]
places where you cannot push you bike are marked with bicycle=no. for example: highway=footway, bicycle=no.

streest where you can normally ride your bike can be marked as with bicycle=dismount, to indicate that you can only push the bike. ex: highway=residential, bicycle=dismount.

**Comment by sensescape** [comment]
Seth, tried this, i don't think it's drawing:
  #copenhagen_line[highway='residential'][bicycle='dismount'] {
    ::road_inline{ line-width:20; line-color:#ff0000; line-dasharray: 2, 1; }
  }

Question for Emil,

Could you send me an example?

**Comment by sensescape** [comment]
What other types to add here ( need all major n minor roads)

#copenhagen_line[highway='residential'][bicycle='dismount'],
#copenhagen_line[highway='primary'][bicycle='dismount'],
#copenhagen_line[highway='secondary'][bicycle='dismount'],
#copenhagen_line[highway='tertiary'][bicycle='dismount'],
#copenhagen_line[highway='pedestrian'][bicycle='dismount'] {
    ::road_inline{ line-width:1.5; line-color:#78c600; line-dasharray: 2, 3; }
  }

**Comment by sethfitz** [comment]
We can surface `bicycle=*` in High Road and use the 3 road classes from that if that's easier...
