### ISSUE TITLE
Tone down motorways

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#27]
tone down in color so that bike lanes are the ones the pop off the map. Better to use color to tone down (more accurate), rather than using lessening line width

Tone down these areas:
http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions#Denmark

**Comment by emiltin** [comment]
bike lanes are not what should pop out, but rather bigger roads where you CAN bike. and perhaps bike routes
