### ISSUE TITLE
Add cobble stone streets

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#29]
add texture

**Comment by sensescape** [comment]
says surface doesn't exist:
[surface='cobblestone']

do i use with highway or copenhagen_line?

**Comment by sethfitz** [comment]
`copenhagen_line`, though that makes it incompatible with high road, so you'd need to draw on top of the existing road lines...  I've been thinking about some revisions to high road to make it more carto friendly, so I'll add this to the list.

If you pull, `surface` is now available.

**Comment by sensescape** [comment]
Merge this in High Road.
