### ISSUE TITLE
Add oneway streets where you are free to bike in any direction

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#3]
![Screen Shot 2013-04-24 at 9 42 22 AM](https://f.cloud.github.com/assets/466585/422816/c6597a6a-ad37-11e2-8434-196ef1412b9c.png)

**Comment by sensescape** [comment]
need help with this one:
http://wiki.openstreetmap.org/wiki/Key:oneway

**Comment by sensescape** [comment]
This one is tricky to symbolize!

**Comment by sensescape** [comment]
http://mapbox.com/carto/api/2.1.0/#line-pattern-file

**Comment by sensescape** [comment]
line-pattern-file

**Comment by sensescape** [comment]
this is not working:
#z14-roads[kind='highway'][oneway='yes'][cycleway='opposite']{
    line-width:10; line-opacity: 1.0; line-color:#ff0000;
  }

major roads and minor roads?

**Comment by sethfitz** [comment]
(@z14)

![screen shot 2013-05-15 at 1 09 28 pm](https://f.cloud.github.com/assets/45/509103/6608737c-bd9b-11e2-86fd-e3662cd47639.png)
