### ISSUE TITLE
Add residential bike lanes at high zooms

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#31]
highway=residential, oneway=yes, cycleway=oppposite

highway=residential, oneway=-1, cycleway=oppposite

**Comment by sensescape** [comment]
visible on opencycle layer

http://www.ibikecph.dk/#!/x5bt0.7hk2e/

**Comment by emiltin** [comment]
residential was just an example. could be any type of street/road.

it could be either a lane (separated by painted line) or track (separated by raised curb)

**Comment by sensescape** [comment]
Note lane drop:

![screen shot 2013-05-20 at 3 24 03 pm](https://f.cloud.github.com/assets/466585/538912/05b894a2-c19c-11e2-8fb4-2b3f8034434c.png)
