### ISSUE TITLE
Filter building labels by area size

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#32]
Need help on this, not sure how to filter by area size like [area>2000000] along with all the types of buildings i'm calling out in below z16

.buildings-labels[zoom>=14][railway='station'],
.buildings-labels[zoom>=14][shop='mall'],
.buildings-labels[zoom>=14][amenity='theatre'],
.buildings-labels[zoom>=14][amenity='university'],
.buildings-labels[zoom>=14][amenity='hospital'],
.buildings-labels[zoom>=14][amenity='public_building']

**Comment by sethfitz** [comment]
`.buildings-labels[zoom>=14][way_area>500]` will catch 82 buildings and skip 6.  (In other words, `way_area` is the field with building size, though I don't know what the units are...probably square meters.)

**Comment by sensescape** [comment]
But how do I write it with all the building types above? Not sure how to do that

**Comment by sethfitz** [comment]
Sorry, should have been `.buildings-labels[zoom>=14][amenity='university'][way_area>500]` (there are 88 of those).

**Comment by sethfitz** [comment]
Is this good to go?

**Comment by sensescape** [comment]
Yes, but not yet finished filtering buildings. BUt yes it's working

On 23 May 2013 14:16, Seth Fitzsimmons notifications@github.com wrote:

> Is this good to go?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stamen/cphbikes/issues/32#issuecomment-18372203
> .

## 

Geraldine Sarmiento
geraldine@stamen.com
415-558-1610

**Comment by sethfitz** [comment]
Cool, I'll assign back to you to close once you're done with the actual filtering.

**Comment by sensescape** [comment]
This is done. But the label is showing up underneath the building

![screen shot 2013-05-24 at 4 57 16 pm](https://f.cloud.github.com/assets/466585/563321/cbd1a5e6-c4cd-11e2-98a6-64b881b2b352.png)
