### ISSUE TITLE
Indicate no access roads

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#33]

**Comment by sensescape** [comment]
access=private
access=restricted

**Comment by sensescape** [comment]
this is  not working:
#z14-roads[kind='minor_road'][access='private']{
    ::road_inline{ line-width:20; line-color:#ff0000; line-dasharray: 5, 1.5; }
  }

tried this too, but not working either:
.copenhagen_line[kind='minor_road'][access='private'],
.copenhagen_line[kind='minor_road'][access='restricted']{
    ::road_inline{ line-width:20; line-color:#ff0000; line-dasharray: 5, 1.5; }
  }

**Comment by sensescape** [comment]
Expose `access=*` via High Road so the same road classifications can be used.

**Comment by sethfitz** [comment]
Do we still need to do this, or is the current way sufficient?

**Comment by sensescape** [comment]
done
