### ISSUE TITLE
Missing buildings at z18

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#35]
despite using building=yes, there are missing buildings at z18

![screen shot 2013-05-22 at 12 55 39 pm](https://f.cloud.github.com/assets/466585/550758/b46c0d48-c319-11e2-81da-c500c4aa13e5.png)

**Comment by sethfitz** [comment]
There are no buildings here, only address points.  Different area with similar symptoms on OSM:

http://www.openstreetmap.org/?lat=55.659026&lon=12.609161&zoom=18&layers=M

**Comment by emiltin** [comment]
yes. some buildinds are missing in cph

**Comment by emiltin** [comment]
i mean they're missing from OSM, so not your problem :-)
