### ISSUE TITLE
Try other treatment for cobblestone streets

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#41]
redo cobblestone street - pattern around the street or next to it, make look more like other streets
keep original styling of cobblestone

**Comment by sensescape** [comment]
this is more like a narrow pathway:
http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#18.00/55.67532/12.57851

**Comment by emiltin** [comment]
some of them. you can see which ones on this map http://www.openstreetmap.org/?lat=55.677048&lon=12.579225&zoom=18&layers=M

**Comment by sensescape** [comment]
Done

![screen shot 2013-05-24 at 4 11 20 pm](https://f.cloud.github.com/assets/466585/563242/53fda6b0-c4c7-11e2-9ce8-0cb550f63ff2.png)
![screen shot 2013-05-24 at 4 11 31 pm](https://f.cloud.github.com/assets/466585/563243/542238ea-c4c7-11e2-826c-2b6efb05c76f.png)
