### ISSUE TITLE
Street labels start at z13

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#47]
see street names z13

**Comment by sensescape** [comment]
http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#13.00/55.6237/12.6171

**Comment by emiltin** [comment]
or maybe it's place/neightborhood labels or shields that's missing. what i noticed what that no labels are showing at all in the example area http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#13.00/55.6237/12.6171

**Comment by sensescape** [comment]
Done

![screen shot 2013-05-24 at 4 31 52 pm](https://f.cloud.github.com/assets/466585/563278/37b8ad76-c4ca-11e2-871b-400147085220.png)
