### ISSUE TITLE
Add highway shields

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#48]
at low zooms

**Comment by sensescape** [comment]
need at z13

**Comment by sethfitz** [comment]
Roads carrying more than 2 routes may be too long to display appropriately:

![screen shot 2013-05-30 at 2 44 43 pm](https://f.cloud.github.com/assets/45/587881/293b2830-c972-11e2-83ad-46ceb1a4331c.png)

I'm checking in styles that handle up to 5 characters in a route name.  That'll look like this:

![screen shot 2013-05-30 at 2 43 34 pm](https://f.cloud.github.com/assets/45/587879/ffb08226-c971-11e2-911e-515542422f49.png)

**Comment by sensescape** [comment]
![screen shot 2013-05-30 at 5 04 45 pm](https://f.cloud.github.com/assets/466585/588481/bef45122-c985-11e2-9a8f-0d9f8116bbcb.png)

done
