### ISSUE TITLE
Add tags to Wiki page so we can collaborate with Emil on what to include at which zoom level

### ISSUE THREAD

**Issue by george08** [ibikecph/cphbikes#5]
We need a place to work with Emil on which tags to include at what level. If you have a better idea than a wiki page on Github, I'm all ears!

Can you please grab the various tags with > 1,000 instances on the map and paste into the wiki? Also, any bike-specific ones?

https://github.com/stamen/cphbikes/wiki/Tag-List

**Comment by sethfitz** [comment]
Wiki's great for now.  Pasted.
