### ISSUE TITLE
construction sites

### ISSUE THREAD

**Issue by emiltin** [ibikecph/cphbikes#57]
we have a a number of major metro construction sites in the city. ex:
http://www.openstreetmap.org/?lat=55.682407&lon=12.571063&zoom=18&layers=M

could we indicate them somehow?

**Comment by sensescape** [comment]
![screen shot 2013-05-24 at 3 52 50 pm](https://f.cloud.github.com/assets/466585/563191/d7bb654e-c4c4-11e2-81f3-eac43b061eeb.png)

added, using a purple hue for construction sites
