### ISSUE TITLE
metro lines

### ISSUE THREAD

**Issue by emiltin** [ibikecph/cphbikes#58]
should we indicate metro lines?

**Comment by sensescape** [comment]
tried these:

.node[subway='yes']
{
  [zoom>=14]
  {
      marker-width: 30;
    marker-fill: #ff0000;
    marker-line-color: darken(#ff0000, 10%);
    }

}

railway=yes not working either

**Comment by sensescape** [comment]
![screen shot 2013-05-28 at 10 51 06 am](https://f.cloud.github.com/assets/466585/574055/38a12e6e-c7bf-11e2-8094-49b56423f510.png)

need help differentiate metro from railway stations

**Comment by sethfitz** [comment]
As far as I can tell, metro stations can only be distinguished from railway stations in Copenhagen due to the use of "Metro" (usually in parentheses) in their name.  I updated the layer SQL to use this as a cue.
