### ISSUE TITLE
service roads should be thinner

### ISSUE THREAD

**Issue by emiltin** [ibikecph/cphbikes#59]
compare:

http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#17.00/55.67361/12.54646
http://www.openstreetmap.org/?lat=55.67355&lon=12.54668&zoom=17&layers=M

**Comment by sensescape** [comment]
![screen shot 2013-05-24 at 3 42 51 pm](https://f.cloud.github.com/assets/466585/563159/4a95ca52-c4c3-11e2-95d6-3720b8902ab1.png)

done
