### ISSUE TITLE
color squares a bit like footways?

### ISSUE THREAD

**Issue by emiltin** [ibikecph/cphbikes#61]
idea: since squares are usually places where you can pusth your bike, but not ride it, perhaps it would make sense to color it a bit like footways? (towards the orange)

it might also avoid any confusion with water (user might think bluish indicate water?)

**Comment by sensescape** [comment]
![screen shot 2013-05-24 at 3 40 01 pm](https://f.cloud.github.com/assets/466585/563152/e7ce1410-c4c2-11e2-9785-1920799f2523.png)

using orange now for steps.  keeping it consistent

orange is now walk your bike
