### ISSUE TITLE
Add POIs

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#7]
- [x] Bike air pumps
- [x] bike service stations
- [x] bike shops 
- [x] bike ramps on steps 
- [x] bike parking 
- [x] barriers that affect cargo bikes 
- [x] traffic signals 
- [x] train/metro stations

**Comment by nvkelso** [comment]
From: http://studio.stamen.com/cphbikes/files/_new%20biz%20docs/Dok.nr%202013-66328%20-%20Workshop%20on%20Map%20Design%20for%20BIke%20Route%20Planner.pdf

**Comment by sensescape** [comment]
![screen shot 2013-05-28 at 11 04 30 am](https://f.cloud.github.com/assets/466585/574129/24d7795e-c7c1-11e2-8d5b-e0a3b0a02fb2.png)
