### ISSUE TITLE
Buildings obscure bike lanes z16 and 17

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#71]

**Comment by sethfitz** [comment]
I'm having trouble tracking down an area that has this problem (though I totally saw it this morning).  Do you still have the link Emil sent?

**Comment by sensescape** [comment]
http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#16.00/55.6765/12.5402

**Comment by sethfitz** [comment]
Solved-ish by rendering buildings below bike lane outlines.  The downside is that the tracks through the main station are drawn on top of the building.  I can address that by splitting railroads from roads and rendering buildings between them, but this is potentially a problem elsewhere.  Thoughts?

![screen shot 2013-05-29 at 1 48 05 pm](https://f.cloud.github.com/assets/45/581514/76ffae3c-c8a1-11e2-9592-fb9f4cb6783b.png)
![screen shot 2013-05-29 at 1 48 29 pm](https://f.cloud.github.com/assets/45/581515/7717c54e-c8a1-11e2-9d42-92e844a0e8c0.png)
![screen shot 2013-05-29 at 1 50 40 pm](https://f.cloud.github.com/assets/45/581516/772bb4be-c8a1-11e2-9908-9af4c5350221.png)

**Comment by sethfitz** [comment]
Splitting railways into their own layer and rendering beneath roads.
