### ISSUE TITLE
'canal' label on dry ground

### ISSUE THREAD

**Issue by emiltin** [ibikecph/cphbikes#77]
http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#16.00/55.6751/12.5799

there seems to be a canal labels that's misplaced

**Comment by sethfitz** [comment]
This is an area label that's being placed on the interior of the canal feature.  Since the feature is U-shaped, it's landing in the middle.  I'm unsure about what we can do about this.

**Comment by emiltin** [comment]
outdated
