### ISSUE TITLE
add bike service stations

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#8]
need more specific, not just bicycle=shop

**Comment by sensescape** [comment]
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle

**Comment by sethfitz** [comment]
![screen shot 2013-05-15 at 12 30 48 pm](https://f.cloud.github.com/assets/45/508940/0bcdd9ba-bd96-11e2-93ac-b36f84a6c92f.png)
