### ISSUE TITLE
style bike ramps on steps, add to other zooms

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#9]
http://wiki.openstreetmap.org/wiki/Key:ramp

**Comment by sensescape** [comment]
http://wiki.openstreetmap.org/wiki/Bicycle_tags_map

**Comment by sensescape** [comment]
Maybe try this?
[ramp:bicycle=yes][highway="steps"]

**Comment by sensescape** [comment]
Looks like layer with:
"id": "copenhagen_line",

Needs to have:
"table": "(SELECT way, highway, bicycle, 'ramp:bicycle', steps, route, aeroway, ncn, rcn, lcn FROM copenhagen_line) as map_stuff",

But `ramp:bicycle` and `steps` don't exist in the DB.

**Comment by sensescape** [comment]
Pleas reassign back to GS when that data is reimported to the DB.

**Comment by sethfitz** [comment]
Added `ramp:bicycle` to the import and layer definition.  `#copenhagen_line['ramp:bicycle'='yes'][highway="steps"]` should surface data now.

**Comment by sensescape** [comment]
Blue indicates ramps on steps

![screen shot 2013-05-24 at 4 21 31 pm](https://f.cloud.github.com/assets/466585/563256/bb388696-c4c8-11e2-8b55-61d8517a5f41.png)
